### PR TITLE
feat: solve deretfibonacci chall

### PR DESCRIPTION
**Pull request by 53buahapel**
test passed

apel@unkown:~/myfile/github/Hacktoberfest2024$ python3 Test_DeretFibonacci.py 
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
apel@un

### CODE REVIEW

**Comment by 53buahapel** [comment]
kak boleh tolong merge lagi ga aku pengen dapet 4 pull :)

**Comment by 53buahapel** [comment]
H3lp

**Comment by 53buahapel** [comment]
aku langsung commit semua aja deh :')
@Gutserk

**Comment by Gutserk** [comment]
siap brok

**Pull request merged**
